# Generated by Django 5.1.1 on 2024-10-04 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_critique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="critique",
            name="note",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
