# Generated by Django 5.1.1 on 2024-10-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_critique_note"),
    ]

    operations = [
        migrations.RenameField(
            model_name="critique",
            old_name="title",
            new_name="critique_title",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="LITRevu/app/tickets_img/"
            ),
        ),
    ]
