# Generated by Django 5.1.1 on 2024-10-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_title_critique_critique_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="LITRevu/app/static/tickets_img/"
            ),
        ),
    ]
