# Generated by Django 5.1.1 on 2024-10-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_ticket_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="LITRevu/app/static/tickets_img"
            ),
        ),
    ]
